#!/bin/bash -e

ROOT="$(cd "$(dirname "$0")/.." && pwd)"

cd "${ROOT}/script/tools/golangci-lint"
IMAGE_NAME=action-update-go/lint
docker build -t "$IMAGE_NAME" .
set -x
exec docker run --rm \
  -v "${ROOT}:/src:ro" \
  -w "/src" \
  "$IMAGE_NAME"

