#!/bin/bash -ex

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

GO_VERSION="$(head -n1 Dockerfile | sed -e 's/.*://g' -e 's/ .*//g')"

for f in .github/workflows/*; do
  sed -i '' -e "s/go-version: .*/go-version: '$GO_VERSION'/g" "$f"
done
