#!/bin/bash -e

ROOT="$(dirname "$0")/.."

export GITHUB_EVENT_NAME="${1:-schedule}"
export GITHUB_EVENT_PATH="${ROOT}/test_webhooks/${GITHUB_EVENT_NAME}.json"
export INPUT_LOG_LEVEL=debug
set | grep ^GITHUB_EVENT
go run .

