#!/bin/bash -e

ROOT="$(dirname "$0")/.."

GREEN='\033[0;32m'
NC='\033[0m'

cd "$ROOT"
for i in action-update go; do
  echo -e "${GREEN}> $i${NC}"
  cd $i
  go test -cover ./...
  cd - >/dev/null
  echo
done
